### ISSUE TITLE
I get three dialogs: Error, Sucess and Windows Features

### ISSUE THREAD

**Issue by Samq64** [TurboWarp/packager-extras#1]
After dragging the zip into packager extras, leaving both options checked, and choosing where I want to save the file, it gives me three dialogs stacked on top of each other. Here they are in the order they appeared:

First:
![Screenshot 2021-07-05 200945](https://user-images.githubusercontent.com/81489795/124525658-06adff80-ddce-11eb-976d-ffd4a5b4e561.png)
Second:
![Screenshot 2021-07-05 201016](https://user-images.githubusercontent.com/81489795/124525667-0d3c7700-ddce-11eb-9832-7a3417f3b803.png)
Third:
![Screenshot 2021-07-05 201045](https://user-images.githubusercontent.com/81489795/124525672-10cffe00-ddce-11eb-9c33-d0f9c96bc43b.png)
Could you please explain why all three of these dialogs are appearing at the same time and what they mean?

**Comment by Samq64** [comment]
I installed the feature from the third dialog and now it's working fine. Closing as resolved. (Sorry for making an issue for this.)

**Comment by GarboMuffin** [comment]
Here's what happened:

 - One of the libraries that TurboWarp Packager Extras uses apparently depends on a .NET Framework that isn't preinstalled, so Windows tries suggests installing it
 - The library thus fails to run and an error is shown
 - Error handling is broken, so the app thinks everything went perfectly fine and displays a success message

I'll be fixing these in the next few days
