### ISSUE TITLE
How to upload custom icon for exe.

### ISSUE THREAD

**Issue by AbelTheTable** [TurboWarp/packager-extras#101]
I wanna change the icon of the electron exe file to a custom icon file I made. I've already made the icon but I don't know how to change it. It said that you were able to change it in the packager extras but it didn't do anything.

**Comment by Mickmick2012** [comment]
reset icon cache (restart windows or use a program to do it)
since you said

> It said that you were able to change it in the packager extras but it didn't do anything.

**Comment by AbelTheTable** [comment]
Do I just go: Windows, Power, restart? 

Also it didn't give me an option to upload an icon.

**Comment by Mickmick2012** [comment]
no, do Windows, Power , shutdown, then turn it back on. (Should work)

**Comment by Mickmick2012** [comment]
resetting only works when the icon is uploaded to the exe, you can change the icon in another way by making a shortcut then selecting the exe then going to properties then select an icon, or, you can use a third party app, like resource hacker to change the icon (in ressource hacker : select exe > open with > resource hacker > action > replace icon) (Note that you may need an ico file)

**Comment by AbelTheTable** [comment]
I just got it to work. All you needed to do was upload the icon into the page icon setting on the normal Packager. Then upload the zip to the extras packager which will fix the icon.

**Comment by NewPlayer23-Minecraft** [comment]
my icon does not work even when i **upload** the **.ico** file for it

**Comment by Mickmick21** [comment]
> my icon does not work even when i **upload** the **.ico** file for it

Please don't [necropost](https://en.wiktionary.org/wiki/necropost), it's annoying.
The advice I posted back then posted is probably outdated. 
If you have any problems, make a new issue.

**Comment by GarboMuffin** [comment]
This is a bug tracker not a forum. Its fine to comment on old things. If we didn't want you to, we would turn off that ability.

**Comment by GarboMuffin** [comment]
Their comment is unhelpful for other reasons though, and probably still justifies a new issue with actual details

**Comment by Mickmick21** [comment]
> This is a bug tracker not a forum. Its fine to comment on old things. If we didn't want you to, we would turn off that ability.

Sorry, sometimes I don't think twice before commenting.
