### ISSUE TITLE
Problem with creating an exe apllication Version 1.5 Windows 11

### ISSUE THREAD

**Issue by FarbrikStrom** [TurboWarp/packager-extras#108]
Hello, I would have a question about why it says that the ZIP file is used elsewhere at the same time, although I have no other program open, would be happy about an answer
![Error 29 12 2023 17_03_35](https://github.com/TurboWarp/packager-extras/assets/155179473/e2f50364-833f-42eb-b021-7d2d4d37c094)

Yeah I'm German

**Comment by GarboMuffin** [comment]
that's a bit weird isn't it

we definitely close the file before calling iscc, so, uh, antivirus interference maybe?

**Comment by FarbrikStrom** [comment]
that didn't helped

**Comment by FarbrikStrom** [comment]
That helped thanks :)

For others who see this post. If you have 2 antivirus programs on your computer, delete one of them then it will work again.
