### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by CreatorYo** [TurboWarp/packager-extras#109]
It keeps showing "Virus Detected" so it won't let me run my file.

**Comment by GarboMuffin** [comment]
what antivirus and what virus?

**Comment by CreatorYo** [comment]
Windows Antivirus.

**Comment by FarbrikStrom** [comment]
I have the same Problem. I have Trojanaer

**Comment by GarboMuffin** [comment]
I'm going to close this as a duplicate of https://github.com/TurboWarp/packager-extras/issues/27
