### ISSUE TITLE
McAfee quarantines app due to Suspect!98a5d9f41aaf

### ISSUE THREAD

**Issue by CloutFor10BucksGitHub** [TurboWarp/packager-extras#11]
Whenever I try to open the installer (or even restore it!!!!), my antivirus automatically quarantines the app. Here is a screenshot of my issue:
![when the turbowarp is sus (1)](https://user-images.githubusercontent.com/92274296/136712058-995289b8-ec91-4f25-b1aa-6d25410fb964.png)
_sus thing in there..._

**Comment by GarboMuffin** [comment]
:/

if you downloaded it from https://github.com/TurboWarp/packager-extras/releases then it's perfectly safe

**Comment by GarboMuffin** [comment]
Consolidating into https://github.com/TurboWarp/packager-extras/issues/27
