### ISSUE TITLE
Unverified Publisher

### ISSUE THREAD

**Issue by CreatorYo** [TurboWarp/packager-extras#111]
How do I make it so my app is a verified publisher? Because I think that, that may be the issue why it's showing that my app is a virus, it may be something to do with the installer.

**Comment by GarboMuffin** [comment]
It requires code signing certificates which are quite expensive. Best of luck: https://www.google.com/search?q=windows%20code%20signing

Making an installer instead of just a zip is probably more likely to trigger those warnings but it can happen with either, really.
