### ISSUE TITLE
cant make sb3 to exe file 

### ISSUE THREAD

**Issue by OSAMAZEADA** [TurboWarp/packager-extras#117]
![image](https://github.com/TurboWarp/packager-extras/assets/160229851/787df9e2-51a2-4ba4-874b-498dd53bac5d)

**Comment by GarboMuffin** [comment]
Use https://packager.turbowarp.org/, use the Electron environment, then upload that zip into Packager Extras. Don't upload your project alone. Extras doesn't know how to add Electron.
