### ISSUE TITLE
Publish on the Microsoft Store

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/packager-extras#12]
We seem to have a lot of issues with antiviruses that we may be able to avoid by publishing on there

**Comment by ThunderGuy77** [comment]
That sounds like a good idea

**Comment by RayFB-13** [comment]
That sounds like an awesome idea!

**Comment by mdoryammilwalrus** [comment]
That sounds like a good idea - however a better GUI may be needed.
Another option for MS Store version is for it to be a packager version combined with extras to be only one packager app.

**Comment by GarboMuffin** [comment]
It would be better for TurboWarp Desktop and Packager Extras to merge
