### ISSUE TITLE
The Packager Extras zip file is not Unix-friendly

### ISSUE THREAD

**Issue by ntvmb** [TurboWarp/packager-extras#138]
I've been using the TurboWarp Packager Extras under Wine with no issues until I updated to 1.7.0, but all of those issues had to do with the zip file itself.
- The zip file uses `\` as the path separator, which doesn't play well with graphical archive managers that expect the path separator to be `/`.
- `unzip` correctly identifies that the path separator is `\`, but breaks permissions in every sub-directory under `_internal`, so Packager Extras will not run until the permissions are manually corrected with `chmod`.

**Comment by GarboMuffin** [comment]
wine isn't really "supported" but in 1.8.0 it should Just Work

**Comment by ntvmb** [comment]
I noticed. (to be fair, it was an easy fix)
