### ISSUE TITLE
[Errno 13] Permission denied on everything

### ISSUE THREAD

**Issue by lukas-studio-tv** [TurboWarp/packager-extras#14]
This shows always when opening a zip file (even as administrator):
(using Electron and latest extras version (1.2.0))

![image](https://user-images.githubusercontent.com/62482747/144707960-66e3ecae-f64b-47df-a4fe-eddf7dd38005.png)

I tried moving into different directories and different permisions but nothing worked.
And using ResourceHacker just breaks the executable (throws an error when launching.)

**Comment by lukie6007** [comment]
the exact same happens to me, I have no idea whats happening I would try disabling antivirus

**Comment by GarboMuffin** [comment]
Please see if this still happens in v1.3.0: https://github.com/TurboWarp/packager-extras/releases

If it still happens, take a screenshot of the new error message (it should contain significantly more detail)

**Comment by GarboMuffin** [comment]
(see above, open new issue if still happens)
