### ISSUE TITLE
-3 error 

### ISSUE THREAD

**Issue by DavidDryden** [TurboWarp/packager-extras#17]
![image](https://user-images.githubusercontent.com/93728850/149564653-acf98e02-f1c4-4f23-b3b4-2f28af391d48.png)
got this error
when opening 1.20

**Comment by GarboMuffin** [comment]
This might be fixed in v1.3.0. If not, reopen this issue.

https://github.com/TurboWarp/packager-extras/releases/tag/v1.3.0
