### ISSUE TITLE
Cannot create installer.

### ISSUE THREAD

**Issue by SalamanderManiacsYT** [TurboWarp/packager-extras#20]
Every time I try to make an installer, I always get this error: 
![image](https://user-images.githubusercontent.com/100527358/155900435-1fddaa0e-a463-4258-9aaa-16e01575e414.png)
Is there any way I can fix this?
This only happens when creating an installer.

**Comment by GarboMuffin** [comment]
This might be fixed in v1.3.0. If not, reopen this issue with a screenshot of the new error message (it should contain significantly more detail)

https://github.com/TurboWarp/packager-extras/releases
