### ISSUE TITLE
Not Opening In Windows 8

### ISSUE THREAD

**Issue by Shubh-Khandelwal** [TurboWarp/packager-extras#25]
Hello ,
I was trying to opening in Windows 8,Build 9200 and it is showing this ⬇.
![Screenshot (486)](https://user-images.githubusercontent.com/81914882/162947736-f9236bc8-28aa-4415-a779-32b988f10251.png)
I am [laddu_1106](https://scratch.mit.edu/users/laddu_1106) on scratch and CodingWithShubh#8153 on discord.
Please solve this issue as soon as possible

**Comment by GarboMuffin** [comment]
This is probably fixed in v1.3.0

https://github.com/TurboWarp/packager-extras/releases
