### ISSUE TITLE
utf-8" codec can't decode byte in position 28:  invalid start byte

### ISSUE THREAD

**Issue by 1215chen** [TurboWarp/packager-extras#35]
Debug info: 
at run_ command in app. py:  61  at create installer in app. py:  221  at run in app. py:  400  
at run in app. py:  279 (1.4.0 Windows 10 AMD64) Debug info: 
![image](https://user-images.githubusercontent.com/87510367/186105414-39f55613-186c-44e5-b0df-85863202f933.png)

**Comment by 1215chen** [comment]
In version 1.4.0

**Comment by 1215chen** [comment]
Operating environment: Windows 10 operating system version 21h1 (version 19043.1766)

**Comment by SIPC** [comment]
![image](https://user-images.githubusercontent.com/92251518/213363387-6c28c5d5-3737-4d11-a97e-49b47fbcd9ed.png)

**Comment by GarboMuffin** [comment]
We believe this will be fixed in v1.5.0, to be released later today
