### ISSUE TITLE
Wacatac.h!ml

### ISSUE THREAD

**Issue by GroceyLot** [TurboWarp/packager-extras#38]
So I packaged a project, used extras, ran setup and then windows security came up with a warning about a trojan. The trojan was called Wacatac.h!ml and It said it was severe. I tried repackaging the project and it still came up. What is this?

**Comment by GarboMuffin** [comment]
we would suggest not using extras in that case

**Comment by riwi07** [comment]
> So I packaged a project, used extras, ran setup and then windows security came up with a warning about a trojan. The trojan was called Wacatac.h!ml and It said it was severe. I tried repackaging the project and it still came up. What is this?

I'm having the exact same issue. Same trojan that it says and everything.
