### ISSUE TITLE
antivirus (MacAfee) deletes the entire 1.0

### ISSUE THREAD

**Issue by RayFB-13** [TurboWarp/packager-extras#4]
I download 1.0 and my antivirus deletes it, making me use 0.2. Thank you.

**Comment by Barthdry** [comment]
It deletes it because the file may not have any signatures and would be a little vulnerable.

**Comment by Barthdry** [comment]
It just thinks it is a virus.

**Comment by GarboMuffin** [comment]
Consolidating into https://github.com/TurboWarp/packager-extras/issues/27
