### ISSUE TITLE
result setup exe after putting in a win32/64 bit electron gives wacatac trojan warning on windows defender

### ISSUE THREAD

**Issue by riwi07** [TurboWarp/packager-extras#40]
When I select a zip file that was packaged with electron for win 32 and 64 bit and turn it into a standalone setup exe, windows defender gives me a warning for a wacatac trojan when executing it. I run windows 10. Is this an issue with the packager extras, windows defender, or is my computer feeding any exe generated by it the trojan? Old setup exes from about a month ago do not have this issue.
![Screenshot (882)](https://user-images.githubusercontent.com/113483852/190033244-78290930-5cf9-41a7-8cb9-e9c6e7c68b3b.png)

**Comment by PPPDUD** [comment]
If you have such issues, please go to #27.

**Comment by PPPDUD** [comment]
@GarboMuffin Please close this.

**Comment by PPPDUD** [comment]
> @GarboMuffin Please close this.

@GarboMuffin

**Comment by GarboMuffin** [comment]
Closing as a duplicate of #27
