### ISSUE TITLE
Issue with making an installer

### ISSUE THREAD

**Issue by Lisrealsm64** [TurboWarp/packager-extras#58]
![Screenshot_20230118_043558](https://user-images.githubusercontent.com/115091404/213310891-5c2d33c8-4c95-4a5a-9d17-4d4ba968c042.png)

**Comment by GarboMuffin** [comment]
temporary solution: rename your project file so it doesn't have a ":" character in it

**Comment by Lisrealsm64** [comment]
it's actually not a colon, it's a special unicode character that looks like
a colon, so it shouldn't be an issue

**Comment by RedGuy12** [comment]
it's an issue because it's an unrecognized character

**Comment by Lisrealsm64** [comment]
SHUT UP LUKE NOBODY CARES

On Fri, Mar 10, 2023 at 10:28 AM Luke Scutary ***@***.***> wrote:

> 😑
> "-.- . . .--. / --- ..- - -.-.-- / ... .... ..- - / ..- .--. -.-.-- / ..
> .----. -- / .-- --- .-. -.- .. -. --. / -.-. .- .--. . / .-. .- -.-. .
> .-.-.-"
> Jack Philips
>


-- 
Caden Sikes
                        DTSOI
                        Class of 2028

**Comment by Lisrealsm64** [comment]
bro

On Fri, Mar 10, 2023 at 10:59 AM Caden Sikes ***@***.***> wrote:

> SHUT UP LUKE NOBODY CARES
>
> On Fri, Mar 10, 2023 at 10:28 AM Luke Scutary ***@***.***> wrote:
>
>> 😑
>> "-.- . . .--. / --- ..- - -.-.-- / ... .... ..- - / ..- .--. -.-.-- / ..
>> .----. -- / .-- --- .-. -.- .. -. --. / -.-. .- .--. . / .-. .- -.-. .
>> .-.-.-"
>> Jack Philips
>>
>
>
> --
> Caden Sikes
>                         DTSOI
>                         Class of 2028
>


-- 
Audrey McLarty
Don Tyson School of Innovation
Class of 2028

**Comment by Lisrealsm64** [comment]
yeah what he said

On Fri, Mar 10, 2023 at 10:59 AM Caden Sikes ***@***.***> wrote:

> SHUT UP LUKE NOBODY CARES
>
> On Fri, Mar 10, 2023 at 10:28 AM Luke Scutary ***@***.***> wrote:
>
>> 😑
>> "-.- . . .--. / --- ..- - -.-.-- / ... .... ..- - / ..- .--. -.-.-- / ..
>> .----. -- / .-- --- .-. -.- .. -. --. / -.-. .- .--. . / .-. .- -.-. .
>> .-.-.-"
>> Jack Philips
>>
>
>
> --
> Caden Sikes
>                         DTSOI
>                         Class of 2028
>


-- 

*DTSOI STUDENTKYPTEN SLOAN*
*CLASS OF 2028*

**Comment by Lisrealsm64** [comment]
All,

There are teachers in here. Please do not reply all to this anymore. Thank
you.
