### ISSUE TITLE
Web browser not downloading file 

### ISSUE THREAD

**Issue by kk5dire** [TurboWarp/packager-extras#6]
My web browser receives the following when attempting to download "error when connecting to the network; Virus Detected" 
Msedge: 92.0.902.73 (Official build) (64-bit)
Rev: cad199e39220991414cd71868a619fff614880c7
Windows: Windows 11 OS Version 21H2 (Build 22000.132)
Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.73
Flags: --flag-switches-begin --enable-features=msEdgeTabGroups --flag-switches-end
Sorry if this issue is easily fixed.
The same effect applies to most chromium browsers, no it does not let me override this or turn it off (that I see of.)
This image will show via the downloads panel
![image](https://user-images.githubusercontent.com/52354566/129683181-db55d02c-5d30-4d7b-bdf3-a5f7701a62b2.png)

Your time is much obliged cheers!

**Comment by RayFB-13** [comment]
look [here](https://github.com/TurboWarp/packager-extras/issues/4),
thanks

**Comment by kk5dire** [comment]
> look [here](https://github.com/TurboWarp/packager-extras/issues/4),
> thanks
@RayFB-13 
Yes, but how does it help the situation. I made the issue separate as an anti-virus can be disabled why (as my knowledge) a system wide anti-virus cannot

**Comment by GarboMuffin** [comment]
The whole antivirus situation here is very unfortunate and there's not a whole lot I can directly do about it :(

**Comment by kk5dire** [comment]
> The whole antivirus situation here is very unfortunate and there's not a whole lot I can directly do about it :(
Was just wondering if the issue was anything my fault. No worries

**Comment by GarboMuffin** [comment]
Consolidating into https://github.com/TurboWarp/packager-extras/issues/27
