### ISSUE TITLE
Issues with Icon

### ISSUE THREAD

**Issue by echoless3484** [TurboWarp/packager-extras#63]
I'm trying to make an offline copy of Submersible for my friend, and the icon only shows up when its not named Submersible, here:

![image](https://user-images.githubusercontent.com/109392419/224440423-9b470e66-f2ac-4642-9ecb-e9dd9f0a6d9d.png)
And when its named anything else:
![image](https://user-images.githubusercontent.com/109392419/224440469-0e82a68e-f0b5-4f60-b121-8935deaa6e0e.png)

**Comment by GarboMuffin** [comment]
Seems like it's being cached by Windows

It'll probably work if your restart your computer

**Comment by Mickmick2012** [comment]
maybe reset your icon cache ?

**Comment by echoless3484** [comment]
Thank you very much, this worked

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
