### ISSUE TITLE
1.5.0 gets detected as a virus

### ISSUE THREAD

**Issue by HangingWithCMM** [TurboWarp/packager-extras#66]
![Screenshot 2023-03-18 162148](https://user-images.githubusercontent.com/87918339/226136729-bef2c946-87d6-4769-a471-0bc377ee0f17.png)

**Comment by Mickmick2012** [comment]
Avast ,Jiangmin and AVG is known for false reports

**Comment by Mickmick2012** [comment]
you should report to Avast Jiangmin and AVG that this is not a virus

**Comment by GarboMuffin** [comment]
I have sent samples of 1.5.0 to AVG, Avast, and Jiangmin. There is nothing further we can do.

For Jiangmin in particular, I will note that [if you Google Jiangmin](https://www.google.com/search?q=Jiangmin), you find a bunch of people complaining about it reporting false positives in popular pieces of software like VLC.
