### ISSUE TITLE
Json Extension outputs errors and doesn't function when packaged

### ISSUE THREAD

**Issue by Mistium** [TurboWarp/packager-extras#68]
Getting these error messages and I presume it is to do with the unsandboxed extensions.
I think it completely stops the JSON extension from functioning correctly, is there any way to fix this or do I have to write a JSON parser

I have confirmed it is the json extension that messes with the packager somehow. Tried to run my project through packager again with the json elements removed from my .icn file renderer and it works as if it was never broken. Narrowed it down to the get item of array block

Here is a log of the errors that I have no idea how to read

The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. (250) <URL>

VM101681:58 vm Tried to deserialize sprite specific monitor sound_volume but could not find sprite Origin OS.
Q.write @ VM101681:58
VM101681:58 vm Tried to deserialize sprite specific monitor data_listcontents but could not find sprite Origin OS.
Q.write @ VM101681:58
VM101681:58 vm Tried to deserialize sprite specific monitor data_variable but could not find sprite Origin OS.
Q.write @ VM101681:58
VM101681:58 vm Tried to deserialize sprite specific monitor data_variable but could not find sprite Origin OS.
Q.write @ VM101681:58
VM101681:58 vm Tried to deserialize sprite specific monitor data_variable but could not find sprite Origin OS.
Q.write @ VM101681:58
VM101681:58 vm Tried to deserialize sprite specific monitor data_variable but could not find sprite Origin OS.
Q.write @ VM101681:58
VM101681:58 vm Tried to deserialize sprite specific monitor data_variable but could not find sprite Origin OS.
Q.write @ VM101681:58
VM101681:58 vm Tried to deserialize sprite specific monitor data_variable but could not find sprite Origin OS.
Q.write @ VM101681:58
VM101681:58 vm Tried to deserialize sprite specific monitor data_variable but could not find sprite Origin OS.
Q.write @ VM101681:58
VM101681:58 vm Tried to deserialize sprite specific monitor data_variable but could not find sprite Origin OS.
Q.write @ VM101681:58
VM101681:58 vm Tried to deserialize sprite specific monitor data_variable but could not find sprite Origin OS.
Q.write @ VM101681:58
VM101681:58 vm Tried to deserialize sprite specific monitor data_variable but could not find sprite Origin OS.
Q.write @ VM101681:58
VM101681:58 vm Tried to deserialize sprite specific monitor data_variable but could not find sprite Origin OS.
Q.write @ VM101681:58
VM101681:58 vm Tried to deserialize sprite specific monitor data_variable but could not find sprite Origin OS.
Q.write @ VM101681:58

VM101681:70 Connecting to wss://clouddata.turbowarp.org with ID origin-network, username player7529

VM101681:58 vm IR: operator_not: missing input OPERAND Objectfields: {}[[Prototype]]: Objectconstructor: ƒ Object()assign: ƒ assign()create: ƒ create()defineProperties: ƒ defineProperties()defineProperty: ƒ defineProperty()entries: ƒ entries()freeze: ƒ freeze()fromEntries: ƒ fromEntries()getOwnPropertyDescriptor: ƒ getOwnPropertyDescriptor()getOwnPropertyDescriptors: ƒ getOwnPropertyDescriptors()getOwnPropertyNames: ƒ getOwnPropertyNames()getOwnPropertySymbols: ƒ getOwnPropertySymbols()getPrototypeOf: ƒ getPrototypeOf()hasOwn: ƒ hasOwn()is: ƒ is()isExtensible: ƒ isExtensible()isFrozen: ƒ isFrozen()isSealed: ƒ isSealed()keys: ƒ keys()length: 1name: "Object"preventExtensions: ƒ preventExtensions()prototype: {constructor: ƒ, __defineGetter__: ƒ, __defineSetter__: ƒ, hasOwnProperty: ƒ, __lookupGetter__: ƒ, …}seal: ƒ seal()setPrototypeOf: ƒ setPrototypeOf()values: ƒ values()arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()id: "ay|"inputs: {}[[Prototype]]: Objectnext: nullopcode: "operator_not"parent: "w#"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
Q.write @ VM101681:58

VM101681:70 WebSocket connected

**Comment by Mystium-YT** [comment]
Actually, I have no idea what is causing it other than the fact it is the JSON extension. It works in some situations but not others and I'm just confused. Wrote a JSON parser in scratch so I'm fine but idk

**Comment by GarboMuffin** [comment]
post the project project file here publicly or send it to contact at turbowarp dot org

**Comment by Mystium-YT** [comment]
[Origin OS V2.4.7.txt](https://github.com/TurboWarp/packager-extras/files/11153186/Origin.OS.V2.4.7.txt)
just rename it to a .sb3. This is a slightly older version that doesn't have my JSON parser in but works fine in editor just not when packaged

**Comment by GarboMuffin** [comment]
custom extensions in the packager used to be pretty bugger; at some point they became better and I did not check to close this

if it still happens & you still care, press "Reset all options" at the bottom and it'll start working
