### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by WuXiHe** [TurboWarp/packager-extras#73]
![image](https://user-images.githubusercontent.com/128343281/235558680-65c556f8-e911-4807-8ffd-dfaa75217e99.png)

**Comment by Mickmick2012** [comment]
i don't think you can put \\ to access a file

**Comment by GarboMuffin** [comment]
we think this is related to antiviruses; closing as a duplicate of https://github.com/TurboWarp/packager-extras/issues/27
