### ISSUE TITLE
Software Gives Error After Selecting/Dropping Zip File

### ISSUE THREAD

**Issue by SuperSonic472** [TurboWarp/packager-extras#8]
Hey It's Supersonic61223 again lol When Opening my ZIP file for the EXE version of a game I'm working on it errors with a message about permission being denied
![image](https://user-images.githubusercontent.com/64370131/132255852-ace0e6be-3c38-407b-9f46-c8d5f5f56637.png)

**Comment by GarboMuffin** [comment]
Does it always do that?

**Comment by SuperSonic472** [comment]
Always

**Comment by KDE-PLASMA5** [comment]
> Hey It's Supersonic61223 again lol When Opening my ZIP file for the EXE version of a game I'm working on it errors with a message about permission being denied
> ![image](https://user-images.githubusercontent.com/64370131/132255852-ace0e6be-3c38-407b-9f46-c8d5f5f56637.png)

Hey @SuperSonic472 . I found the fix for your problem. You have to do the .zip file that all the assets and the app were in, not the app itself. hope that helps!

**Comment by GarboMuffin** [comment]
Please see if this still happens in v1.3.0: https://github.com/TurboWarp/packager-extras/releases

If it still happens, take a screenshot of the new error message (it should contain significantly more detail)

**Comment by GarboMuffin** [comment]
(see above, open new issue if still happens)
