### ISSUE TITLE
My dumbahh closed my issue

### ISSUE THREAD

**Issue by DogeMaster69420** [TurboWarp/packager-extras#89]
What happened is in the image:

![image](https://github.com/TurboWarp/packager-extras/assets/112454109/7f35ac23-414b-4837-a724-1ee3af54e269)

For some reason when I open a Election Zip it says this even though I manually added chrome_100_percent.pak in the zip.

**Comment by DogeMaster69420** [comment]
I closed it last time like a idiot/

**Comment by GarboMuffin** [comment]
In the packager, scroll to the bottom, press export settings, then put that JSON in zip and upload it here or a site like send.vis.ee
